export const CHUNK_QUALITY_BAR_COPY = {
  noResult: "还没有结果",
  liveRunning: "运行中",
  checkpointIncomplete: "断点未完成",
  diff: "改写对照",
  showAll: "显示全部",
  noReviewChunks: "暂无需处理块",
  failedChunks: "重跑失败",
  noFailedChunks: "暂无重跑失败块",
  highRisk: "高风险",
  noHighRiskChunks: "暂无高风险块",
  changedChunks: "新增/删除",
  numberRisk: "数字风险",
  citationRisk: "引用风险",
  rerunFailure: "重跑失败",
  source: "原文",
  rewrite: "改写",
  highRiskRewrite: "高风险改写",
  risk: "表达提示",
  needsReview: "需处理",
  stable: "稳定",
  expansion: "扩写比",
  citationMissing: "引用缺失",
  colloquialIntroduced: "新增口语",
  protectedTokens: "结构锁定",
  useRewrite: "采用改写",
  useSource: "保留原文",
  defaultChoice: "默认采用",
  confirmedChoice: "已确认",
  rerunRisky: "重跑需处理",
  rerunStrategy: "策略",
  reviewReason: "原因",
  targetedRerun: "定向重跑",
  feedbackPlaceholder: "补充重跑要求（可选）",
  lastFeedback: "上次意见",
  sourceFallback: "校验失败",
  customChoice: "人工修改",
  styleMetrics: "降检测指标",
  burstinessRatio: "句长突发",
  passiveDensity: "被动密度",
  chengyuDensity: "成语密度",
  paragraphLengthCv: "段长CV",
  adjacentParagraphUniformity: "邻段齐整",
} as const;

export const T = CHUNK_QUALITY_BAR_COPY;
